name: zzekak_client

packages:
  - app
  - core
  - data
  - util


scripts:
  analyze:
    exec: flutter analyze
    description: 모든 코드의 분석을 실행합니다.

  i:
    exec: flutter pub get
    description: 모든 패키지를 설치합니다.

  codegen:
    run: dart run ./app/asset_management_script.dart && melos exec flutter pub run build_runner build --delete-conflicting-outputs
    description: 모든 코드를 생성합니다.

  update:
    exec: flutter pub upgrade
    description: 모든 패키지를 업데이트합니다.

  outdated:
    exec: flutter pub outdated
    description: 모든 패키지의 업데이트 가능 여부를 확인합니다.