name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.3.2

# Add regular dependencies here.
dependencies:
  equatable: 2.0.5

dev_dependencies:
  lints: 3.0.0
  analyzer: 6.0.0
  coverage: 1.7.1
  test: 1.24.9
  build_runner: 2.4.7
