name: zzekak_custom_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.5.3

# Add regular dependencies here.
dependencies:
  analyzer: 6.0.0
  analyzer_plugin: 0.11.3
  logger: 2.4.0
  custom_lint_builder: 0.5.7

dev_dependencies:
  lints: ^2.1.0
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter
