include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - /**/*.g.dart
    - /**/*.mocks.dart
  plugins:
    - custom_lint
  errors:
    constant_identifier_names: true

linter:
  rules:
    constant_identifier_names: false
