name: zzekak
description: 즐거움을 향해 달려가는 수다쟁이! 약속은 내가 지켜
publish_to: none
version: 1.0.0+1

environment:
  sdk: 3.5.3

dependencies:
  bloc: 8.1.4
  core:
    path: ../core/
  cupertino_icons: 1.0.6
  data:
    path: ../data/
  dart_scope_functions: 0.1.4
  equatable: 2.0.5
  firebase_core: 3.4.0
  firebase_messaging: 15.1.0
  flutter:
    sdk: flutter
  flutter_asset_builder:
    git:
      url: https://github.com/WongueShin/flutter_asset_builder
  flutter_bloc: 8.1.6
  flutter_dotenv: ^5.2.1
  flutter_svg: 2.0.9
  get_it: 7.6.7
  go_router: 12.1.1
  kakao_flutter_sdk: 1.9.1+2
  logger: 2.4.0
  permission_handler: 11.3.1
  rxdart: ^0.27.7
  sign_in_with_apple: 6.1.0
  svg_path_parser: 1.1.2
  url_launcher: 6.3.1

dev_dependencies:
  analyzer: 6.0.0
  build_runner: 2.4.13
  custom_lint: null
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.4.1
  go_router_builder: 2.7.0
  zzekak_custom_lint:
    path: ../zzekak_custom_lint/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
