name: zzekak
description: 즐거움을 향해 달려가는 수다쟁이! 약속은 내가 지켜
publish_to: none
version: 1.0.0+1

environment:
  sdk: 3.2.3

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core/
  data:
    path: ../data/

  cupertino_icons: 1.0.6
  flutter_svg: 2.0.9
  go_router: 12.1.1
  get_it: 7.6.4
  injectable: 2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  flutter_launcher_icons: 0.13.1
  build_runner: 2.4.7
  injectable_generator: 2.4.1
  analyzer: 6.0.0
  custom_lint:
  zzekak_custom_lint:
    path: ../zzekak_custom_lint/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
