name: zzekak
description: 즐거움을 향해 달려가는 수다쟁이! 약속은 내가 지켜
publish_to: none
version: 1.0.0+1

environment:
  sdk: 3.3.2

dependencies:
  core:
    path: ../core/
  cupertino_icons: 1.0.6
  data:
    path: ../data/
  dart_scope_functions: 0.1.4
  flutter:
    sdk: flutter
  flutter_asset_builder:
    git:
      url: https://github.com/WongueShin/flutter_asset_builder
  flutter_svg: 2.0.9
  get_it: 7.6.7
  go_router: 12.1.1
  kakao_flutter_sdk: 1.9.1+2
  sign_in_with_apple: 6.1.0

dev_dependencies:
  analyzer: 6.0.0
  build_runner: 2.4.7
  custom_lint: null
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.4.1
  go_router_builder: 2.7.0
  zzekak_custom_lint:
    path: ../zzekak_custom_lint/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
