name: zzekak
description: 즐거움을 향해 달려가는 수다쟁이! 약속은 내가 지켜
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core/
  data:
    path: ../data/

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
