name: util
description: A starting point for Dart libraries or applications.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.5.3

# Add regular dependencies here.
dependencies:
  core:
    path: ../core
  get_it: 7.6.7

dev_dependencies:
  lints: 3.0.0
  build_runner: 2.4.13
